# -*- coding: utf-8 -*-
"""Modelo previsão de consumo.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LsscA81th2iNfzKPoEEQ9FgseGxcRJxg

## Importando bibliotecas necessárias
"""

# Instalar Prophet
#pip install prophet

# Importar bibliotecas
import os
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from prophet import Prophet
from sklearn.metrics import mean_absolute_error, mean_squared_error
from sklearn.model_selection import train_test_split
import pymysql
from dotenv import load_dotenv

# Carregar variáveis de ambiente do arquivo .env
load_dotenv()

# 🔹 Configuração do Banco de Dados MySQL
DB_USERNAME = os.getenv("DB_USERNAME")
DB_PASSWORD = os.getenv("DB_PASSWORD")
DB_NAME = os.getenv("DB_NAME")
DB_HOST = os.getenv("DB_HOST")

# Função para estabelecer conexão com o banco de dados MySQL
def get_db_connection():
    """Estabelece e retorna uma conexão com o banco de dados MySQL."""
    try:
        conn = pymysql.connect(
            host=DB_HOST,
            user=DB_USERNAME,
            password=DB_PASSWORD,
            database=DB_NAME,
            cursorclass=pymysql.cursors.DictCursor  # Retorna os resultados como dicionário
        )
        print(f"✅ Conectado ao banco de dados: {DB_NAME}")
        return conn
    except pymysql.MySQLError as e:
        print(f"❌ Erro ao conectar ao banco de dados: {e}")
        return None

# # Função para puxar dados do banco e carregar em um DataFrame
# def puxar_dados_do_banco():
#     """Puxa os dados da tabela e carrega no DataFrame."""
#     conn = get_db_connection()
#     if conn:
#         try:
#             query = "SELECT timestamp FROM medicao_consumo;;"  # Consulta para pegar todos os dados da tabela
#             df = pd.read_sql(query, conn)  # Carregar os dados diretamente para um DataFrame
#             print("✅ Dados carregados com sucesso do banco!")
#             return df
#         except Exception as e:
#             print(f"❌ Erro ao executar consulta: {e}")
#         finally:
#             conn.close()
#             print("🔌 Conexão fechada.")
#     else:
#         return None

# # 🔹 Carregar os dados do banco
# data = puxar_dados_do_banco()

def visualizar_dados_do_banco():
    # Estabelece a conexão com o banco de dados
    conn = get_db_connection()
    
    if not conn:
        print("❌ Não foi possível conectar ao banco de dados.")
        return None

    try:
        with conn.cursor() as cursor:
            # Consulta SQL para pegar todas as medições
            query = """
                SELECT id, timestamp, consumoTotal
                FROM medicao_consumo;
            """
            cursor.execute(query)
            
            # Pega todos os resultados
            todas_as_medicoes = cursor.fetchall()

            # Verifica se há resultados
            if todas_as_medicoes:
                # Converte para um DataFrame do pandas para uso em modelos
                df = pd.DataFrame(todas_as_medicoes)
                return df  # Retorna o DataFrame com os dados
            else:
                print("Nenhuma medição encontrada.")
                return None
        
    except pymysql.MySQLError as e:
        print(f"❌ Erro ao realizar a consulta: {e}")
        return None
    
    finally:
        conn.close()

# Chama a função e captura os dados
data = visualizar_dados_do_banco()

# Verificar os primeiros registros
# if data is not None:
#     print("aqui")
#     print(data["consumoTotal"].head())

# from google.colab import files

# # Fazer upload do arquivo manualmente
# uploaded = files.upload()

# # Carregar o dataset (ajuste o nome do arquivo conforme necessário)
# data = pd.read_csv("Dataset_Simulado_de_Consumo.csv", sep=',')

# # Exibir as primeiras linhas
# data.head()

"""## Visualizando dados"""

data.head()

"""## Implementação do modelo Prophet

preparação dos dados
"""
data["consumoTotal"] = pd.to_numeric(data["consumoTotal"], errors='coerce')
print(data[data["consumoTotal"].isna()])
data["consumoTotal"] = data["consumoTotal"].astype(str)
data["consumoTotal"] = data["consumoTotal"].str.replace(',', '.', regex=False)
data["consumoTotal"] = data["consumoTotal"].astype(float)
data.info()

# Converter a coluna 'timestamp' para formato de data
data['timestamp'] = pd.to_datetime(data['timestamp'])

# Selecionar apenas as colunas necessárias para o Prophet
df = data[['timestamp', 'consumoTotal']].rename(columns={'timestamp': 'ds', 'consumoTotal': 'y'})

# Garantir que a série temporal tenha uma frequência uniforme
df = df.set_index("ds").asfreq("10min").reset_index()


# Exibir os primeiros registros formatados
df.head()

# Dividir os dados aleatoriamente em 80% treino e 20% teste
train, test = train_test_split(df, test_size=0.2)

# Ordenar os dados pelo timestamp dentro de cada conjunto para manter a coerência temporal
train = train.sort_values(by="ds")
test = test.sort_values(by="ds")

# Exibir os tamanhos dos conjuntos
print(f"Tamanho do treino: {len(train)}, Tamanho do teste: {len(test)})")

# Criar e treinar o modelo Prophet
modelo = Prophet()
# modelo.add_seasonality(name="diario", period=24, fourier_order=10)  # Padrão diário
# modelo.add_seasonality(name="semanal", period=24*7, fourier_order=5)  # Padrão semanal
modelo.fit(train)

# Criar um dataframe com datas futuras para o período de teste
future = modelo.make_future_dataframe(periods=len(test), freq='10min')

# Fazer a previsão
forecast = modelo.predict(future)

# Selecionar apenas as previsões correspondentes ao período de teste
forecast_test = forecast.iloc[-len(test):]

# Exibir as primeiras previsões
forecast_test[['ds', 'yhat']].head()

test['y'] = test['y'].fillna(0)
nan_count = test['y'].isna().sum()
print(f"NaN na coluna 'y': {nan_count}")

# Calcular Erro Absoluto Médio (MAE)
mae = mean_absolute_error(test['y'], forecast_test['yhat'])

# Calcular Erro Quadrático Médio (MSE)
mse = mean_squared_error(test['y'], forecast_test['yhat'])

# Calcular Raiz do Erro Quadrático Médio (RMSE)
rmse = np.sqrt(mse)

print(f"MAE: {mae:.2f}")
print(f"MSE: {mse:.2f}")
print(f"RMSE: {rmse:.2f}")

plt.figure(figsize=(12, 6))

# Plotar valores reais do conjunto de teste
plt.plot(test['ds'], test['y'], label='Valores Reais', color='blue')

# Plotar previsões do modelo
plt.plot(forecast_test['ds'], forecast_test['yhat'], label='Previsão Prophet', color='red')

plt.title("Comparação: Previsões vs. Valores Reais")
plt.xlabel("Data")
plt.ylabel("Consumo Total de Energia")
plt.legend()
plt.show()

# Plotar os componentes da previsão (tendência e sazonalidade)
modelo.plot_components(forecast)
plt.show()

# Criar um DataFrame comparativo entre valores reais e previstos
df_comparacao = pd.DataFrame({
    "timestamp": test["ds"].values,
    "valor_real": test["y"].values,
    "previsao_prophet": forecast_test["yhat"].values,
    "erro_absoluto": np.abs(test["y"].values - forecast_test["yhat"].values)
})

# Exibir as primeiras linhas do DataFrame
df_comparacao.head()

# Função para salvar previsões no banco de dados
def salvar_previsao_no_banco(forecast_test):
    """Insere as previsões do modelo Prophet na tabela 'previsao_consumo'."""
    conn = get_db_connection()
    
    if not conn:
        print("❌ Não foi possível conectar ao banco de dados para salvar as previsões.")
        return
    
    try:
        with conn.cursor() as cursor:
            # Query para inserir as previsões na tabela previsao_consumo
            query = """
                INSERT INTO previsao_consumo (timestamp, consumo)
                VALUES (%s, %s)
            """
            
            # Itera sobre as previsões e insere no banco
            for _, row in forecast_test.iterrows():
                timestamp = row['ds']
                previsao = row['yhat']
                cursor.execute(query, (timestamp, previsao))
            
            # Commit para salvar as alterações no banco de dados
            conn.commit()
            print("✅ Previsões salvas com sucesso no banco de dados!")
    
    except pymysql.MySQLError as e:
        print(f"❌ Erro ao salvar as previsões no banco de dados: {e}")
    
    finally:
        conn.close()

# Função para treinar, testar e prever as medições futuras
def treinar_e_prever():
    # Dividir os dados aleatoriamente em 80% treino e 20% teste
    train, test = train_test_split(df, test_size=0.2)

    # Ordenar os dados pelo timestamp dentro de cada conjunto para manter a coerência temporal
    train = train.sort_values(by="ds")
    test = test.sort_values(by="ds")

    # Criar e treinar o modelo Prophet
    modelo = Prophet()
    modelo.fit(train)

    # Criar um dataframe com datas futuras para o período de teste
    future = modelo.make_future_dataframe(periods=len(test), freq='10min')

    # Fazer a previsão
    forecast = modelo.predict(future)

    # Selecionar apenas as previsões correspondentes ao período de teste
    forecast_test = forecast.iloc[-len(test):]

    # Exibir as primeiras previsões
    print(forecast_test[['ds', 'yhat']].head())

    # Calcular as métricas de avaliação
    test['y'] = test['y'].fillna(0)
    nan_count = test['y'].isna().sum()
    print(f"NaN na coluna 'y': {nan_count}")

    mae = mean_absolute_error(test['y'], forecast_test['yhat'])
    mse = mean_squared_error(test['y'], forecast_test['yhat'])
    rmse = np.sqrt(mse)

    print(f"MAE: {mae:.2f}")
    print(f"MSE: {mse:.2f}")
    print(f"RMSE: {rmse:.2f}")

    plt.figure(figsize=(12, 6))
    # Plotar valores reais do conjunto de teste
    plt.plot(test['ds'], test['y'], label='Valores Reais', color='blue')
    # Plotar previsões do modelo
    plt.plot(forecast_test['ds'], forecast_test['yhat'], label='Previsão Prophet', color='red')
    plt.title("Comparação: Previsões vs. Valores Reais")
    plt.xlabel("Data")
    plt.ylabel("Consumo Total de Energia")
    plt.legend()
    plt.show()

    # Plotar os componentes da previsão (tendência e sazonalidade)
    modelo.plot_components(forecast)
    plt.show()

    # Salvar as previsões no banco
    salvar_previsao_no_banco(forecast_test)

    # Agora prever as próximas medições para o próximo dia (por exemplo, usando 24 horas a mais)
    future_next_day = modelo.make_future_dataframe(periods=24*4, freq='10min')  # 24h * 4 (a cada 15 minutos)
    
    # Prever as futuras medições
    forecast_next_day = modelo.predict(future_next_day)

    # Exibir as previsões do próximo dia
    forecast_next_day[['ds', 'yhat']].tail()

    # Salvar as previsões futuras no banco
    salvar_previsao_no_banco(forecast_next_day.tail(24*4))  # Ajustar o número de previsões se necessário

# Chame a função para treinar, testar e prever as medições futuras
treinar_e_prever()
